## demo Vectorized vs Non-Vectorized Code
* `inspired by Andrew Ng's course at deeplearning.ai`
* Use vectorized approaches for better computation
* Broadcasting
    * helps avoid for-loops through automatic transformation of vectors
    * potential issues with rank 1 arrays

### performance for vectorized vs nonvectorized code

In [102]:
import numpy as np

a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [103]:
# vectorized version
import time

a = np.random.rand(1000000) # million dim array
b = np.random.rand(1000000) # million dim array

tic1 = time.time()
# vectorized
c = np.dot(a,b)
toc1 = time.time()




# nonvectorized, for loop version takes much longer
c = 0
tic2 = time.time()
for i in range(1000000):
    c += a[i] * b[i]
    
toc2 = time.time()

print("Vectorized version: {0:.3f} ms".format(1000*(toc1-tic1)))
print("For-loop version: {0:.3f} ms".format(1000*(toc2-tic2)))

x_faster = (toc2-tic2)/(toc1-tic1)
print("Vectorized version is {0:.3f} times faster".format(x_faster))

Vectorized version: 0.784 ms
For-loop version: 491.510 ms
Vectorized version is 626.799 times faster


#### AVOID FOR LOOPS!
* ... whenever possible

```





```
### Use np vector/matrix operations
* np vectors/arrays can receive most operations directly, without a for-loop

In [104]:
'''
example: create a matrix with percentage contribution to 
         each column
'''

# first, build a random normal, 
#   5x4 matrix with values mu=50, sigma=40
A = np.abs(40*np.random.randn(5, 4) + 50)

print(A)

[[ 58.53348993  58.20226079  61.45613714  66.33386725]
 [ 16.63980157   3.01826404   6.90667932  96.88348889]
 [ 49.59134337  31.47327713 115.11978712  39.63892068]
 [ 32.39991298  83.0155741   67.20459335  74.44083023]
 [ 56.48383827  92.04295588  55.72913828  67.52746688]]


In [105]:
# sum columns vertically, store in vector
col_sums = A.sum(axis=0) 
col_sums

array([213.64838613, 267.75233194, 306.41633521, 344.82457393])

In [106]:
# build matrix of element percentages
percentages = 100*A/col_sums.reshape(1,4)
percentages

array([[27.39711308, 21.73734973, 20.05641674, 19.23698955],
       [ 7.78840499,  1.12725966,  2.25401799, 28.09645722],
       [23.21166299, 11.75462298, 37.56972912, 11.49538742],
       [15.16506329, 31.00461292, 21.93244473, 21.58802935],
       [26.43775565, 34.37615471, 18.18739143, 19.58313646]])

In [107]:
# verify
percent_sums = percentages.sum(axis=0)
percent_sums

array([100., 100., 100., 100.])

```





```
### Broadcasting
* np vectors/arrays automatically change shape for certain operations
* avoid using rank 1 arrays `.shape=(n,)`

In [108]:
d = np.random.randn(5)
d

array([ 0.7927525 , -1.00646762,  0.68635007,  0.6052297 ,  0.54565976])

In [109]:
# a rank 1 array is neither a row vector nor column vector
d.shape

(5,)

In [110]:
# note that the rank 1 array has the same output when transposed
print(d)
print(d.T)

[ 0.7927525  -1.00646762  0.68635007  0.6052297   0.54565976]
[ 0.7927525  -1.00646762  0.68635007  0.6052297   0.54565976]


In [111]:
# difficult to predict outcome of the dot product of a
#  rank 1 array with itself
is_this_a_dot_product = np.dot(d,d.T)
print("What does this number represent?: {}".format(is_this_a_dot_product))


What does this number represent?: 2.7765575772878286


In [112]:
# recommendation is don't use rank 1 arrays like shape (5,)
# instead, explicitly declare the shape when building the array:
e = np.random.randn(5,1)
print(e)
print()
print(e.T)

[[-1.15544681]
 [-0.33317615]
 [-0.14645179]
 [-1.81561415]
 [-2.01734266]]

[[-1.15544681 -0.33317615 -0.14645179 -1.81561415 -2.01734266]]


#### [outer product of a vector:](https://ipfs.io/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/wiki/Outer_product.html)

In [113]:
print(np.dot(e, e.T))

[[1.33505733 0.38496731 0.16921725 2.09784558 2.33093213]
 [0.38496731 0.11100634 0.04879424 0.60491932 0.67213045]
 [0.16921725 0.04879424 0.02144813 0.26589994 0.29544344]
 [2.09784558 0.60491932 0.26589994 3.29645474 3.66271587]
 [2.33093213 0.67213045 0.29544344 3.66271587 4.06967139]]


#### g is broadcast to a (2,3) matrix to accommodate addition

In [114]:
f = np.random.randn(2, 3) # f.shape = (2, 3)
g = np.random.randn(2, 1) # g.shape = (2, 1)
h = f + g
h.shape

(2, 3)

#### Not every shape will broadcast with numpy
* if you can't predict what the outcome should be of a potential broadcast, reconsider your strategy

In [115]:
# cannot broadcast these shapes
i = np.random.randn(4, 3) # i.shape = (4, 3)
j = np.random.randn(3, 2) # j.shape = (3, 2)
k = i*j

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

### Perform a dot product betw two matrices
* not the shape result

In [116]:
# note dot product shape result
l = np.random.randn(12288, 150) # l.shape = (12288, 150)
m = np.random.randn(150, 45) # m.shape = (150, 45)

# perform dot product
n = np.dot(l,m)
n.shape

(12288, 45)

#### Equivalent for loop and vectorized form of summing matrix w/ vector

In [117]:
# vectorize a for loop
# o.shape = (3,4)
# p.shape = (4,1)

o = np.random.randn(3, 4)
p = np.random.randn(4, 1)

# not vectorized form
# for i in range(3):
#     for j in range(4):
#         q[i][j] = o[i][j] + p[j]
        
# vectorized form        
q = o + p.T
q

array([[-0.17864392,  0.3377534 , -0.04837904,  1.06869887],
       [-0.72491527, -2.69985519,  0.62838398,  2.30728136],
       [-0.47859891, -0.55159259, -0.31342458,  0.85736906]])

#### Broadcast vector for element-wise multiplication with matrix

In [118]:
r = np.random.randn(3,3)
s = np.random.randn(3,1)
t = r*s
print(t)

# as expected, it's commutative
u = s*r
print(u)

print(t==u)

[[ 0.61511136 -0.90393123 -0.41371254]
 [-0.33064669 -0.46787484  0.62698729]
 [-0.21014577  0.22333625  0.31273106]]
[[ 0.61511136 -0.90393123 -0.41371254]
 [-0.33064669 -0.46787484  0.62698729]
 [-0.21014577  0.22333625  0.31273106]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
